Models/FreeboardPart.cs
using System;
using System.Collections.Generic;
using Orchard.ContentManagement;

namespace Freeboard.Models {
    public class FreeboardPart : ContentPart<FreeboardPartRecord> {

        public string Configuration {
            get {
                return string.IsNullOrEmpty(Record.Configuration) ? "{}" : Record.Configuration;
            }
            set { Record.Configuration = value; }
        }

        public string EditorTheme {
            get {
                return string.IsNullOrEmpty(Record.EditorTheme) ? "cobalt" : Record.EditorTheme;
            }
            set { Record.EditorTheme = value; }
        }

        public bool IsValid() {
            return !String.IsNullOrEmpty(Configuration);
        }

        public IEnumerable<string> AvailableThemes {
            get { return new[] { "3024-day", "3024-night", "ambiance-mobile", "ambiance", "base16-dark", "base16-light", "blackboard", "cobalt", "eclipse", "elegant", "erlang-dark", "lesser-dark", "mbo", "mdn-like", "midnight", "monokai", "neat", "neo", "night", "paraiso-dark", "paraiso-light", "pastel-on-dark", "rubyblue", "solarized", "the-matrix", "tomorrow-night-eighties", "twilight", "vibrant-ink", "xq-dark", "xq-light" }; }
        }

        public bool Editable { get; set; }

    }
}

Models/FreeboardPartRecord.cs
using System.ComponentModel.DataAnnotations;
using Orchard.ContentManagement.Records;
using Orchard.Data.Conventions;

namespace Freeboard.Models {
    public class FreeboardPartRecord : ContentPartRecord {

        [StringLengthMax]
        public virtual string Configuration { get; set; }

        [StringLength(128)]
        public virtual string EditorTheme { get; set; }
    }
}

Controllers/FreeboardController.cs
using System;
using System.Text;
using System.Web.Mvc;
using Freeboard.Models;
using Orchard;
using Orchard.ContentManagement;
using Orchard.Localization;
using Orchard.Services;

namespace Freeboard.Controllers {

    public class FreeboardController : Controller {

        protected Localizer T { get; set; }
        private readonly IOrchardServices _services;
        private readonly IJsonConverter _jsonConverter;

        public FreeboardController(IOrchardServices services, IJsonConverter jsonConverter) {
            _services = services;
            _jsonConverter = jsonConverter;
            T = NullLocalizer.Instance;
        }

        public ActionResult Index(int id) {
            var item = _services.ContentManager.Get(id).As<FreeboardPart>();

            if (item == null) {
                return new HttpNotFoundResult();
            }

            if (!_services.Authorizer.Authorize(Orchard.Core.Contents.Permissions.ViewContent, item, T("Access to this dashboard is controlled"))) {
                if (!User.Identity.IsAuthenticated) {
                    System.Web.Security.FormsAuthentication.RedirectToLoginPage(Request.RawUrl);
                }
                return new HttpUnauthorizedResult();
            }

            item.Editable = _services.Authorizer.Authorize(Orchard.Core.Contents.Permissions.EditContent);

            return View("Index", item);
        }

        [HttpGet]
        public string Load(int id) {
            Response.ContentType = "application/json";
            Response.ContentEncoding = Encoding.UTF8;

            var item = _services.ContentManager.Get(id).As<FreeboardPart>();
            if (item == null) {
                return "{\"status\":404}";
            }

            if (!_services.Authorizer.Authorize(Orchard.Core.Contents.Permissions.ViewContent, item)) {
                return "{\"status\":401}";
            }

            try {
                dynamic parsedJson = _jsonConverter.Deserialize(item.Configuration);
                parsedJson.status = 200;
                return _jsonConverter.Serialize(parsedJson, JsonFormat.Indented);
            } catch (Exception) {
                return "{\"status\":500}";
            }
        }

        [HttpPost]
        public string Save() {
            Response.ContentType = "application/json";
            Response.ContentEncoding = Encoding.UTF8;

            int id;
            if (!int.TryParse((Request.Form["id"] ?? "0"), out id)) {
                return "{\"status\":400}";
            }

            var item = _services.ContentManager.Get(id).As<FreeboardPart>();
            if (item == null) {
                return "{\"status\":404}";
            }

            var data = Request.Form["data"];
            if (data == null) {
                return "{\"status\":400}";
            }

            if (!_services.Authorizer.Authorize(Orchard.Core.Contents.Permissions.EditContent, item)) {
                return "{\"status\":401}";
            }

            try {
                dynamic parsedJson = _jsonConverter.Deserialize(data);
                item.Configuration = _jsonConverter.Serialize(parsedJson, JsonFormat.Indented);
            } catch (Exception) {
                return "{\"status\":500}";
            }

            return "{\"status\":200}";
        }
    }

}

Views/EditorTemplates/Parts/Freeboard.cshtml
@model Freeboard.Models.FreeboardPart

@{
    
    Script.Require("jQuery").AtHead();

    const string root = "https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.12.0/";

    Style.Include(root + "codemirror.min.css").AtHead();
    Style.Include(root + "addon/display/fullscreen.min.css").AtHead();
    Style.Include(root + "addon/fold/foldgutter.min.css").AtHead();
    Style.Include(root + "addon/dialog/dialog.css").AtHead();
    Style.Include(root + "addon/hint/show-hint.min.css").AtHead();
    Style.Include(root + "theme/" + Model.EditorTheme + ".min.css").AtHead();

    Script.Include(root + "codemirror.min.js").AtHead();
    Script.Include(root + "mode/javascript/javascript.min.js").AtHead();
    Script.Include(root + "addon/display/fullscreen.min.js").AtHead();
    Script.Include(root + "addon/fold/foldcode.min.js").AtHead();
    Script.Include(root + "addon/fold/foldgutter.min.js").AtHead();
    Script.Include(root + "addon/fold/xml-fold.min.js").AtHead();
    Script.Include(root + "addon/dialog/dialog.min.js").AtHead();
    Script.Include(root + "addon/search/search.min.js").AtHead();
    Script.Include(root + "addon/search/searchcursor.min.js").AtHead();
    Script.Include(root + "addon/search/jump-to-line.min.js").AtHead();
    Script.Include(root + "addon/search/match-highlighter.min.js").AtHead();
    Script.Include(root + "addon/hint/show-hint.min.js").AtHead();
    Script.Include(root + "addon/hint/anyword-hint.min.js").AtHead();
}

<script>
$(document).ready(function () {

    var xml = $('#Freeboard_Configuration');

    var editor = CodeMirror.fromTextArea(xml[0], {
        mode: 'javascript',
        json: true,
        matchBrackets: true,
        lineNumbers: true,
        theme: '@(Model.EditorTheme)',
        extraKeys: {
            "Ctrl-Space": "autocomplete",
            "Ctrl-Q": function (cm) { cm.foldCode(cm.getCursor()); },
            "Ctrl-S": function () { $('.CodeMirror').closest('form').find(':submit').click(); },
            "F11": function (cm) {
                cm.setOption("fullScreen", !cm.getOption("fullScreen"));
            },
            "Esc": function (cm) {
                if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
            },
            "Tab": function (cm) {
                var spaces = Array(3).join(" ");
                cm.replaceSelection(spaces);
            }
        },
        foldGutter: true,
        gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
    });

    editor.setSize("100%", Math.round(window.innerHeight * .7));
});
</script>

<div class="editor-field">
    @Html.LabelFor(x => x.Configuration, T("Configuration"))
    @Html.TextAreaFor(x => x.Configuration)
</div>
<div class="hint">
    <strong>F11</strong>: <span>Full Screen</span>,
    <strong>Esc</strong>: <span>Exit Full Screen</span>,
    <strong>Ctrl-S</strong>: <span>Save</span>,
    <strong>Ctrl-Space</strong>: <span>Auto Complete</span>,
    <strong>Ctrl-F</strong>: <span>Find</span>,
    <strong>Ctrl-G</strong>: <span>Find next</span>,
    <strong>Shift-Ctrl-G</strong>: <span>Find previous</span>,
    <strong>Shift-Ctrl-F</strong>: <span>Replace</span>,
    <strong>Shift-Ctrl-R</strong>: <span>Replace all</span>.
</div>

<fieldset>
    @Html.LabelFor(m => m.EditorTheme, T("Editor Theme"))
    @Html.DropDownListFor(m => m.EditorTheme, new SelectList(Model.AvailableThemes, Model.EditorTheme))
    <span class="hint">@T("Change this code editor's theme.")</span>
</fieldset>

Views/Freeboard/Index.cshtml
@using Orchard.ContentManagement
@using Orchard.Core.Title.Models
@model Freeboard.Models.FreeboardPart
@{
    var title = Model.As<TitlePart>().Title;
}<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>@(title)</title>
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="viewport" content="width = device-width, initial-scale = 1, user-scalable = no" />
    <link href="css/freeboard.min.css" rel="stylesheet" />
    <script>
        //<!--
        var settings = {
            load: '@(Url.Action("Load","Freeboard", new { id = Model.Id }))',
            save: '@(Url.Action("Save","Freeboard"))',
            token: '@(Html.AntiForgeryTokenValueOrchard())',
            id: @(Model.Id),
            home: '@(Url.Content("~/"))'
        };
        //-->
    </script>
    <script src="js/freeboard.thirdparty.min.js"></script>
    <script type="text/javascript">
        head.js("js/freeboard_plugins.min.js",
            function () {
                $(function () {
                    freeboard.initialize(true);

                    @if (Model.Configuration != "{}") {
                        <text>
                        var data = @Html.Raw(Model.Configuration);
                        freeboard.loadDashboard(data, function () {
                            freeboard.setEditing(false);
                        });
                        </text>
                    }
                });
            });
    </script>
</head>
<body>
    <div id="board-content">
        <img id="dash-logo" data-bind="attr:{src: header_image}, visible:header_image()">
        <div class="gridster responsive-column-width">
            <ul data-bind="grid: true">
			</ul>
        </div>
    </div>
    <header id="main-header" data-bind="if:allow_edit">
        <div id="admin-bar">
            <div id="admin-menu">
                <div id="board-tools">
                    <h1 id="board-logo" class="title bordered">@(title)</h1>
                    <div id="board-actions">
                        <ul class="board-toolbar vertical">
                            <li data-bind="click: goHome"><i class="icon-home icon-white"></i><label>Home</label></li>
                            <li> </li>
                            <li> </li>
                        </ul>
                        <ul class="board-toolbar vertical">
                            <li data-bind="click: loadDashboardFromOrchard"><i id="full-screen-icon" class="icon-folder-open icon-white"></i><label id="full-screen">Load</label></li>
                            @if (Model.Editable) {
                                <li data-bind="click: saveDashboardToOrchard"><i class="icon-download icon-white"></i><label>Save</label></li>
                            }
                            <li id="add-pane" data-bind="click: createPane"><i class="icon-plus icon-white"></i><label>Add Pane</label></li>
                        </ul>
                    </div>
                </div>
                <div id="datasources">
                    <h2 class="title">DATASOURCES</h2>

                    <div class="datasource-list-container">
                        <table class="table table-condensed sub-table" id="datasources-list" data-bind="if: datasources().length">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Last Updated</th>
                                    <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody data-bind="foreach: datasources">
                                <tr>
                                    <td>
                                        <span class="text-button datasource-name" data-bind="text: name, pluginEditor: {operation: 'edit', type: 'datasource'}"></span>
                                    </td>
                                    <td data-bind="text: last_updated"></td>
                                    <td>
                                        <ul class="board-toolbar">
                                            <li data-bind="click: updateNow"><i class="icon-refresh icon-white"></i></li>
                                            <li data-bind="pluginEditor: {operation: 'delete', type: 'datasource'}">
                                                <i class="icon-trash icon-white"></i>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <span class="text-button table-operation" data-bind="pluginEditor: {operation: 'add', type: 'datasource'}">ADD</span>
                </div>
            </div>
        </div>
        <div id="column-tools" class="responsive-column-width">
            <ul class="board-toolbar left-columns">
                <li class="column-tool add" data-bind="click: addGridColumnLeft"><span class="column-icon right"></span><i class="icon-arrow-left icon-white"></i></li>
                <li class="column-tool sub" data-bind="click: subGridColumnLeft"><span class="column-icon left"></span><i class="icon-arrow-right icon-white"></i></li>
            </ul>
            <ul class="board-toolbar right-columns">
                <li class="column-tool sub" data-bind="click: subGridColumnRight"><span class="column-icon right"></span><i class="icon-arrow-left icon-white"></i></li>
                <li class="column-tool add" data-bind="click: addGridColumnRight"><span class="column-icon left"></span><i class="icon-arrow-right icon-white"></i></li>
            </ul>
        </div>
        <div id="toggle-header" data-bind="click: toggleEditing">
            <i id="toggle-header-icon" class="icon-wrench icon-white"></i>
        </div>
    </header>

    <div style="display:hidden">
        <ul data-bind="template: { name: 'pane-template', foreach: panes}">
		</ul>
    </div>

    <script type="text/html" id="pane-template">
        <li data-bind="pane: true">
            <header>
                <h1 data-bind="text: title"></h1>
                <ul class="board-toolbar pane-tools">
                    <li data-bind="pluginEditor: {operation: 'add', type: 'widget'}">
                        <i class="icon-plus icon-white"></i>
                    </li>
                    <li data-bind="pluginEditor: {operation: 'edit', type: 'pane'}">
                        <i class="icon-wrench icon-white"></i>
                    </li>
                    <li data-bind="pluginEditor: {operation: 'delete', type: 'pane'}">
                        <i class="icon-trash icon-white"></i>
                    </li>
                </ul>
            </header>
            <section data-bind="foreach: widgets">
                <div class="sub-section" data-bind="css: 'sub-section-height-' + height()">
                    <div class="widget" data-bind="widget: true, css:{fillsize:fillSize}"></div>
                    <div class="sub-section-tools">
                        <ul class="board-toolbar">
                            <!-- ko if:$parent.widgetCanMoveUp($data) -->
                            <li data-bind="click:$parent.moveWidgetUp"><i class="icon-chevron-up icon-white"></i></li>
                            <!-- /ko -->
                            <!-- ko if:$parent.widgetCanMoveDown($data) -->
                            <li data-bind="click:$parent.moveWidgetDown"><i class="icon-chevron-down icon-white"></i></li>
                            <!-- /ko -->
                            <li data-bind="pluginEditor: {operation: 'edit', type: 'widget'}"><i class="icon-wrench icon-white"></i></li>
                            <li data-bind="pluginEditor: {operation: 'delete', type: 'widget'}"><i class="icon-trash icon-white"></i></li>
                        </ul>
                    </div>
                </div>
            </section>
        </li>
    </script>

</body>
</html>